### PR TITLE
Modifying test and benchmarks to match log level order

### PR DESCRIPTION
**Pull request by Kanshiroron**

### CODE REVIEW

**Comment by apsdehal** [comment]
Still not passing, if you have time, try one more time otherwise I will push a fix tomorrow.

**Comment by Kanshiroron** [comment]
@apsdehal Sorry I didn't have much time looking into it, but it's very weird to me trying to understand how my changes have broke the test...
The issue is following:
```
$ go test .
--- FAIL: TestLogger_SetFormat (0.00s)
    logger_test.go:157: 
        Want: #1 2019-05-06 10:23:09 logger_test.go:152 ▶ DEB Test
        Have: 
FAIL
FAIL	_/home/kanshi/temp/go-logger	0.001s
```
Which points to:
```
func TestLogger_SetFormat(t *testing.T) {
        var buf bytes.Buffer
        log, err := New("pkgname", 0, &buf)
        if err != nil || log == nil {
                panic(err)
        }
        log.Debug("Test")
        want := time.Now().Format("2006-01-02 15:04:05")
        want = fmt.Sprintf("#1 %s logger_test.go:152 ▶ DEB Test\n", want)
        have := buf.String()
        if have != want {
                t.Errorf("\nWant: %sHave: %s", want, have)
        }
```

If I comment the `t.Errorf("\nWant: %sHave: %s", want, have)` all other tests are working correctly.

**Comment by apsdehal** [comment]
Thanks. I have fixed the tests so the build should be passing now. I have tagged a new release for log level filters as well.

**Comment by Kanshiroron** [comment]
awesome thanks! I indeed didn't have much time to investigate...

**Pull request merged**
